// wirekratos: Wire workspace mode fix package with Kratos integration
// Auto removes -mod=mod flag from Wire-generated files to resolve workspace issues
//
// wirekratos: Kratos 集成的 Wire workspace 模式修复包
// 自动移除 Wire 生成文件中的 -mod=mod 标志，解决 workspace 问题
package main

import (
	"flag"
	"os"
	"path/filepath"
	"strings"

	"github.com/orzkratos/wirekratos/internal/utils"
	"github.com/yyle88/done"
	"github.com/yyle88/erero"
	"github.com/yyle88/must"
	"github.com/yyle88/must/mustslice"
	"github.com/yyle88/osexistpath/osmustexist"
	"github.com/yyle88/runpath"
	"github.com/yyle88/zaplog"
	"go.uber.org/zap"
)

func main() {
	// Log current execution path
	// 记录当前执行路径
	zaplog.LOG.Info("main", zap.String("path", runpath.PARENT.Path()))

	// Define command flags
	// 定义命令标志
	var path string      // Absolute path to wire_gen.go // wire_gen.go 绝对路径
	var name string      // Relative path to wire_gen.go // wire_gen.go 相对路径
	var framework string // Framework name (e.g., kratos) // 框架名称（如 kratos）
	var debug bool       // Enable debug output // 启用调试输出
	flag.StringVar(&path, "path", "", "absolute_path. example: /Users/admin/xx/xx/xx/project/cmd/project/wire_gen.go")
	flag.StringVar(&name, "name", "", "relative_path. example: cmd/project/wire_gen.go")
	flag.StringVar(&framework, "framework", "", "framework name. example: kratos")
	flag.BoolVar(&debug, "debug", false, "debug mode")
	flag.Parse()

	// Log command arguments
	// 记录命令参数
	zaplog.LOG.Info("args", zap.String("path", path), zap.String("name", name), zap.String("framework", framework), zap.Bool("debug", debug))

	// Derive wire_gen.go path from various inputs
	// 从各种输入派生 wire_gen.go 路径
	if path == "" {
		switch {
		case name != "":
			// Use relative path from current DIR // 使用当前 DIR 的相对路径
			path = filepath.Join(utils.PWD(), name)
		case framework != "":
			// Auto detect path based on framework // 基于框架自动检测路径
			switch framework {
			case "kratos":
				path = deriveKratosProjectWireGenPath()
			default:
				panic(erero.New("wrong param"))
			}
		default:
			panic(erero.New("wrong param"))
		}
	}
	zaplog.LOG.Info("derive-wire_gen-path", zap.String("path", path))

	// Replace Wire command line in the file
	// 替换文件中的 Wire 命令行
	replaceWireCommandLine(path, debug)
	zaplog.LOG.Info("done")
}

// replaceWireCommandLine removes -mod=mod flag from Wire-generated file
// Resolves workspace mode issues through go:generate directive modification
//
// replaceWireCommandLine 从 Wire 生成文件中移除 -mod=mod 标志
// 通过修改 go:generate 指令解决 workspace 模式问题
func replaceWireCommandLine(path string, debug bool) {
	// Check file exists and read content
	// 检查文件存在并读取内容
	osmustexist.MustFile(must.Nice(path))
	content := string(done.VAE(os.ReadFile(path)).Nice())
	if debug {
		zaplog.SUG.Info(content)
	}

	// Split into lines for processing
	// 拆分为行进行处理
	sxLines := strings.Split(content, "\n")
	mustslice.Nice(sxLines)

	// Check Wire-generated file signature
	// 检查 Wire 生成文件签名
	const prefixComment = "// Code generated by Wire. DO NOT EDIT."
	must.Equals(sxLines[0], prefixComment)

	// Target line is at index 2 (third line)
	// 目标行在索引 2 处（第三行）
	const index = 2
	must.FALSE(len(sxLines) <= index)

	// Replace -mod=mod flag in go:generate directive
	// 替换 go:generate 指令中的 -mod=mod 标志
	const matchOriginLine = "//go:generate go run -mod=mod github.com/google/wire/cmd/wire"
	const changeToNewLine = "//go:generate go run github.com/google/wire/cmd/wire"
	if sxLines[index] != changeToNewLine {
		must.Equals(sxLines[index], matchOriginLine)

		sxLines[index] = changeToNewLine

		// Write modified content back to file
		// 将修改后的内容写回文件
		newCode := strings.Join(sxLines, "\n")
		if debug {
			zaplog.SUG.Info(newCode)
		}
		must.Done(os.WriteFile(path, []byte(newCode), 0644))
	}
}

// deriveKratosProjectWireGenPath auto derives wire_gen.go path in Kratos projects
// Follows Kratos convention: cmd/PROJECT_NAME/wire_gen.go
//
// deriveKratosProjectWireGenPath 自动派生 Kratos 项目中的 wire_gen.go 路径
// 遵循 Kratos 约定：cmd/项目名/wire_gen.go
func deriveKratosProjectWireGenPath() string {
	// Get current working DIR as project root
	// 获取当前工作 DIR 作为项目根目录
	root := utils.PWD()
	must.Nice(root)
	osmustexist.MustRoot(root)

	// Extract project name from root DIR path
	// 从根 DIR 路径提取项目名
	projectName := filepath.Base(root)
	must.Nice(projectName)

	// Build wire_gen.go path following Kratos convention
	// 按照 Kratos 约定构建 wire_gen.go 路径
	path := filepath.Join(root, "cmd", projectName, "wire_gen.go")
	osmustexist.MustFile(path)
	return path
}
